Base feat
sergey-oreshkin/java-explore-with-me pull request #9
Opened 2022-10-03 14:39 UTC by sergey-oreshkin

2022-10-05 11:25 UTC, EvgenyKoptubenko commented on README.md
> +
Так же нужно делать полное описание проекта. Что он умеет, для чего он. Как его запустить.
Если запускать как-то сложно, то нужно сделать скрипт, который запустит проект.

2022-10-05 11:38 UTC, EvgenyKoptubenko commented
Если проект состоит из нескольких модулей, которые можно запускать вместе, то в проекте должен быть runConfigurations, чтобы другой разработчик мог скачать проект и запустить его не через докер одной кнопкой. Если есть желание, добавь runConfigurations в папку .idea.

Замечание из разряда "можно лучше"

2022-10-05 11:44 UTC, EvgenyKoptubenko commented
Возвращая какой-то объект, желательно возвращать не просто данные, но данные в каком-то "контейнере". Почитай про hateos. Смысл в том, что есть home endpoint, через который дальше проваливаешься к нужным данным

Замечание из разряда "можно лучше"

2022-10-05 11:45 UTC, EvgenyKoptubenko commented
Нигде нет упоминания healthcheck. Т.е. должен быть эндпоинт, доступный всем, обращаясь к которому, будет получен ответ, что у приложения все хорошо или что-то сломалось (например, нет доступа к базе данных)

Замечание из разряда "можно лучше"

2022-10-05 11:50 UTC, EvgenyKoptubenko commented on ewm/src/main/java/ru/practicum/explorewithme/ewm/category/service/CategoryServiceImpl.java
> +        Category oldCategory = categoryRepository.findById(category.getId())
Есть ниже функция getById - получается, что тут функционал задублирован

2022-10-05 11:59 UTC, EvgenyKoptubenko commented on ewm/src/main/java/ru/practicum/explorewithme/ewm/exception/ControllerExceptionHandler.java
> +    public ErrorDto handleHttpMessageNotReadableException(HttpMessageNotReadableException ex) {
метод не отличается от метода handleUnknownException.
В одном методе можно обрабатывать сразу несколько исключений. Попробуй объединить методы, чтобы не было копирования кода

2022-10-05 12:01 UTC, EvgenyKoptubenko commented
В проекте еще не нашел авторизации, ролей пользователей. Попробуй подключить OAUTH2 авторизацию, например, через Google или еще какого поставщика.

Замечание из разряда "можно лучше"

2022-10-05 12:02 UTC, EvgenyKoptubenko commented
Жаль, что нет тестов, но они не обязательны.
Замечание из разряда "можно лучше"

2022-10-05 12:07 UTC, EvgenyKoptubenko commented
Замечания из разряда "Можно лучше" можно не делать - они скорее для сведения.
Есть совсем немного замечаний. Работа сделана очень хорошо.

2022-10-05 12:07 UTC, EvgenyKoptubenko requested changes
Замечания из разряда "Можно лучше" можно не делать - они скорее для сведения.
Есть совсем немного замечаний. Работа сделана очень хорошо.

2022-10-05 16:49 UTC, sergey-oreshkin commented on README.md
> +
сделал конфиг запуска в идее и скрипты для запуска через докер.
полное описание сделать не получится, я не писатель.

2022-10-05 16:50 UTC, sergey-oreshkin commented on ewm/src/main/java/ru/practicum/explorewithme/ewm/category/service/CategoryServiceImpl.java
> +        Category oldCategory = categoryRepository.findById(category.getId())
fix

2022-10-05 16:55 UTC, sergey-oreshkin commented on ewm/src/main/java/ru/practicum/explorewithme/ewm/exception/ControllerExceptionHandler.java
> +    public ErrorDto handleHttpMessageNotReadableException(HttpMessageNotReadableException ex) {
fix

2022-10-05 16:59 UTC, sergey-oreshkin commented
> В проекте еще не нашел авторизации, ролей пользователей. Попробуй подключить OAUTH2 авторизацию, например, через Google или еще какого поставщика.
> 
> Замечание из разряда "можно лучше"

по ТЗ наш сервер работает за gateway с авторизацией и все запросы уже авторизованны.
к томуже сейчас не так-то просто из России получить гугловский токен чтоб настроить OAuth

2022-10-05 17:00 UTC, sergey-oreshkin commented
> Жаль, что нет тестов, но они не обязательны. Замечание из разряда "можно лучше"

тесты я напишу, просто времени не было пока. по крайней мере юнит тесты точно..

2022-10-06 14:24 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Замечания исправлены и проект сделан очень большой. Спасибо.

2022-10-06 16:09 UTC, merged